[package]
name = "echor"
version = "0.1.0"
edition = "2021"
authors = [ "Afshin Karimi <afshinnkarimi@gmail.com>" ]

[dependencies]
clap = "4.5.31"

[dev-dependencies]
assert_cmd = "2.0.16"
predicates = "3.1.3"